.PHONY: clean All

All:
	@echo "----------Building project:[ PECLManglanoRedondoPablo - Debug ]----------"
	@cd "PECLManglanoRedondoPablo" && "$(MAKE)" -f  "PECLManglanoRedondoPablo.mk"
clean:
	@echo "----------Cleaning project:[ PECLManglanoRedondoPablo - Debug ]----------"
	@cd "PECLManglanoRedondoPablo" && "$(MAKE)" -f  "PECLManglanoRedondoPablo.mk" clean
